# Generated by Django 3.0.7 on 2020-06-17 10:49

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('author', models.CharField(max_length=16, verbose_name='author')),
                ('content', models.CharField(max_length=2048, verbose_name='content')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='publish_time')),
                ('category', models.CharField(max_length=30, verbose_name=blog.models.Category)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=16, verbose_name='visitor_name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('comments', models.CharField(max_length=480, verbose_name='comments')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='publish_time')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
